### ISSUE TITLE
Account Compression getter

### ISSUE THREAD

**Issue by ademirag** [Codigo-io/platform#23]
This is not a bug but a feature.
We can provide an SDK getter function that serializes it. This is simple to implement (already implemented in our tests) and a good feature. This also provide Concurrent Tree Merkle headers and the buffered changes which are already shown in the explorers of the Solana

**Comment by ademirag** [comment]
A user can do it with
`ConcurrentMerkleTreeAccount.fromAccountAddress(connection, merkleTreeAddress);`
from
`@solana/spl-account-compression`
Maybe this feature is not so important.

**Comment by JazielGuerrero** [comment]
Ok, closing for now.
